### PR TITLE
Feature create config file

### PR DESCRIPTION
**Pull request by landjea**
I constantly use CrudGenerator for my packages and am always copying/pasting in a common config file. This would make config generation part of the crudgenerator process.

### CODE REVIEW

**Comment by sohelamin** [comment]
@landjea can you explain a little bit more what to do with the config file or en example ?

**Comment by landjea** [comment]
? For config file options....? I don't understand the question. It will create a config file named <crudName>.php in your config folder. It has a stub so it can be customised. Mine has approximately 18 entries I need for each package I wrap up.

**Comment by sohelamin** [comment]
Actually I didn't get what is the benefits of this config file that's why I asked for an example.
Few days earlier I did a custom template for generating the crud stuffs I'm not sure if your purpose is similar to that.
So if you can please give me an example to let me learned it.

**Comment by landjea** [comment]
Really? You couldn't see how a config file could be useful to anyone? It defaulted to "no" so it wasn't created unless desired. Maybe every crud I make uses a different PrimaryKey or table prefix or something. So instead of typing that out every time I set up my stubs to use that instead. Like I said, I used one every single time i used your CRUD so it was useful to at least one of your users. Don't worry about it. When I saw I had to explain how useful a config file was I started creating my own package generator and it is just about done now so I don't need this package anymore.

**Comment by sohelamin** [comment]
@landjea I think you forgot, I was asking an example how it could help use cause I was not getting it.
I already had config file for this package.  I still don't know why you need config file for every crud.

**Comment by sohelamin** [comment]
Instead of generating config file we could enhance or re-use our config file which already exist.
https://github.com/appzcoder/crud-generator/blob/1.0/config/crudgenerator.php
Maybe you didn't notice that.

**Pull request closed without merging**
