### PR TITLE
Adding routePrefix, routePrefixCap and modelNameCap to CrudViewCommand

### PR DESCRIPTION
**Pull request by lk77**
Hello,

i've added routePrefix and routePrefixCap  in CrudView like i did for CrudController
Also, i've added modelNameCap.

i've added a list of available values in crud generator comment in config file.

thanks.

### CODE REVIEW

**Comment by lk77** [comment]
I've also added model namespace segments :

**Usage :**

`{{modelNamespace[3]}}`
return the third segment of modelNamespace or empty if not exists

**Comment by lk77** [comment]
Hello,

i've added custom variable to CrudViewCommand :

**Usage** 

`--custom-data="section=User"`
`%%section%% will be replaced by User in all stubs`
`Variables can be separated by commas`

**Comment by sohelamin** [comment]
@lk77 Thanks for the contributions (y) 
You missed the `formBodyHtmlForShowView` var fixed at 1078462

**Comment by lk77** [comment]
@sohelamin sorry for that

**Pull request merged**
