### PR TITLE
Fixed file upload snippet to not treat file input like an array

### PR DESCRIPTION
**Pull request by cjke**
The current views generated for file inputs don't facilitate arrays of file uploads, and so the handling of the file data can be greatly simplified (currently, when its treated as an array, its not working at all).

Secondly, updated to use Laravel's built in `store` method as well as the built in `hashName()` method - this will make it far more consistent with how other files are uploaded

Future enhancements would include the migrations for files creating multiple fields (original file name, path, mimetype, etc).

### CODE REVIEW

**Comment by sohelamin** [comment]
Merged at develop branch
I don't think it will support lower than Laravel 5.3

**Comment by cjke** [comment]
Thanks. What minimum requirements are you trying to reach with this project? 

Also, what is the best way to chat about the project? I feel like it gets me about 75% of what I need, but there are some fundamental differences that I would like to introduce - but want to hear about vision first.

**Comment by cjke** [comment]
Also also - in terms of contributing - PR's should point to developer branch yeah?

**Comment by sohelamin** [comment]
The minimum requirement is Laravel 5.1

@cjke You're always welcome to suggest any improvements or features via creating new issue.
You should make PR on develop branch.

**Comment by sohelamin** [comment]
Not working on Laravel 5.1, I had to revert the commit.

**Pull request closed without merging**
