### PR TITLE
 Removed layout master.blade.php in favor of original app.blade.php

### PR DESCRIPTION
**Pull request by eduardoarandah**
- Because the project layout is not relevant for this project.
- Because is impossible to remove if not wanted

Removed lines that copy master.blade.php file
src\Commands\CrudViewCommand.php

In src/stubs/
added a container <div class="container"></div>

### CODE REVIEW

**Comment by sohelamin** [comment]
Do you have any idea if the app layout isn't exists?
Cause the app layout was there until 5.0 version.

**Comment by eduardoarandah** [comment]
I installed Laravel last night and is still there.
Would work out of the box with this crud

El martes, 26 de abril de 2016, Sohel Amin <notifications@github.com>
escribió:

> Do you have any idea if the app layout isn't exists?
> Cause the app layout was there until 5.0 version.
>
> —
> You are receiving this because you authored the thread.
> Reply to this email directly or view it on GitHub
> <https://github.com/appzcoder/crud-generator/pull/77#issuecomment-214827205>
>


-- 
Enviado desde mi móvil

**Comment by sohelamin** [comment]
Which version did you try?
Maybe you ran php artisan make:auth before generating crud stuff.

**Comment by eduardoarandah** [comment]
Latest version.
Ran laravel new projectname
After that make:auth

Is app.blade not coming in original installer? I'm not sure now

El martes, 26 de abril de 2016, Sohel Amin <notifications@github.com>
escribió:

> Which version did you try?
> Maybe you ran php artisan make:auth before generating crud stuff.
>
> —
> You are receiving this because you authored the thread.
> Reply to this email directly or view it on GitHub
> <https://github.com/appzcoder/crud-generator/pull/77#issuecomment-214829935>
>


-- 
Enviado desde mi móvil

**Comment by eduardoarandah** [comment]
You're right, layouts/app.blade.php is present only after make:auth

Anyway, I think layout is still out of this project scope. 

Maybe adding a variable with default value to "layouts.app"
layout=layouts.app

**Pull request merged**
