### PR TITLE
Adding a comment to the routes so the CrudCommand can check the existance of routes

### PR DESCRIPTION
**Pull request by notflip**
I changed the CrudCommand so the generated routes in our routes.php have a comment with the _name_ of the new Route in them. This way we don't overwrite existing routes and we can keep our routes file clean.

### CODE REVIEW

**Comment by sohelamin** [comment]
Can you make again the PR? Maybe you didn't pull the latest commit.

**Comment by sohelamin** [comment]
Did you check it?

**Comment by notflip** [comment]
Hi, What is wrong with this pull request? It's not working?

**Comment by sohelamin** [comment]
On the last update I've changed some logic eg: route group version checking.
And you made PR before my changes thats why I've asked you to amend/modify the PR.

**Pull request closed without merging**
