### PR TITLE
Update validation functionality

### PR DESCRIPTION
**Pull request by ebisbe**
I'd like to be able to set up all the validation for the models instead of just Required. So I reworked the way it pases the data to be able to set it up correctly. 

I don't really like to use # but other symbols are already used ( | , : )

### CODE REVIEW

**Comment by ebisbe** [comment]
For me the main point is being able to use this:

body#text#required_with:title|alpha_num

**Comment by ebisbe** [comment]
@sohelamin  Don't you like that? Any comment?

**Comment by sohelamin** [comment]
@ebisbe Yes I liked :)
But I was no plan to add this functionality for now. I mean the complex validation through the generate command.
Okay I will merge this PR.
Anyway did you test it or did you implement the **required_with**

**Comment by ebisbe** [comment]
@sohelamin I did not implement nothing with required_with. I just made a way to use more than one validation the way it does laravel. That's why I changed your '|' separator for '#'. Because Laravel already implements this. The last part of the # is just to copy paste it. I mean that if there is some error it's from the user itself.

**Pull request merged**
