### PR TITLE
In this fix CamelCase Issue #95 resolved.

### PR DESCRIPTION
**Pull request by tirjok**
Crud Command refactored for camel case issue. Now its fixed

### CODE REVIEW

**Comment by sohelamin** [comment]
Actually I don't like a directory name like **mydirname**
Instead this we can use **my-dir-name**

So we may need to change the view path everywhere.

**Comment by tirjok** [comment]
Yes it is. I am updating and let you know :)

**Comment by tirjok** [comment]
Can you please check now @sohelamin :)

**Comment by sohelamin** [comment]
Thanks for the PR @tirjok 
I need to make some changes cause it is still not working as expected :)

**Comment by ChangePlaces** [comment]
what are the problems, and what's the issue number - let's reopen the issue then!

**Pull request merged**
