### PR TITLE
Fresh code style in controllers

### PR DESCRIPTION
**Pull request by goszowski**

### CODE REVIEW

**Comment by sohelamin** [comment]
@goszowski Thanks for the PR. I've cherry picked some commits.
And no wonder why you did some same changes in different commits :) No problem.

**Comment by sohelamin** [comment]
And if you like to customize the controller. stub it is very easy to do with your own style.
Check this https://github.com/appzcoder/crud-generator/blob/master/doc/templates.md

**Comment by goszowski** [comment]
I know, but some customization is impossible without updates in your package (this changes are in my commits). In addition, it's very difficult to change the template every time, at each project. 
I understand that your package is designed to save time, but not for complications, such as rewriting templates, in order for it to work properly.

**Comment by sohelamin** [comment]
Oh you don't need to customize again & again. Just keep copy of your own templates then reuse your every projects.
I tried to keep the template simple and let user to use from Laravel 5.1+

**Comment by goszowski** [comment]
So we need to split users into versions. 
These can be different directory templates, depending on the version. What do you think of this?
The index method looks rather awkward. I don't know people will think about me if they see this code.
I understand that it is simple version, and  I can then change these methods, but I would like to have OK right after the generation, hope not only me.

**Pull request closed without merging**
