### PR TITLE
Crud-Generator without Form helper

### PR DESCRIPTION
**Pull request by notflip**
I rewrote everything to be able to use this plugin without the form helper. All fields have been replaced by normal fields and I used old() and isset() on variables in the edit field to maintain the form-model binding functionality

### CODE REVIEW

**Comment by sohelamin** [comment]
Hi @notflip 

I appreciate your pull request. Actually most people usually use the form helper. They have different taste.
If we could have an option for both functionality or If we ask users for their choices kinda servey then it will be better for us.
So I will let you know soon once I decided a solution.

**Comment by notflip** [comment]
Good plan! Most people I know prefer not to use it so I'm curious about the results.

**Comment by ebisbe** [comment]
And why not have both? We have config file that can let choose people what to do. I started using the helper and for the moment they are fine to me and haven't had any real issue. But deleting one thing if it's used I think it's not the way to go when we can let people choose. 
A bit of more rework and would be perfect for all.

**Comment by sohelamin** [comment]
Right. We could have both options.
If you guys can make it please proceed or I will add the option later :)

**Comment by notflip** [comment]
I have time from next week! Will review the code and adjust, prepare where
needed.

2016-04-27 21:02 GMT+02:00 Sohel Amin <notifications@github.com>:

**Comment by sohelamin** [comment]
Sounds great! Thank you @notflip for your effort.

**Comment by sohelamin** [comment]
You can make another PR if you do as we discussed.

**Pull request closed without merging**
